"""
Bootstrap router — xử lý provider setup, auth, và .env generation.
"""

import os
import json
import asyncio
from pathlib import Path

import httpx
from fastapi import APIRouter, HTTPException
from fastapi.responses import JSONResponse
from pydantic import BaseModel

router = APIRouter()

ENV_FILE     = Path("/config/.env")
CONFIG_FILE  = Path("/config/providers.json")

# GitHub Device Flow constants
GITHUB_CLIENT_ID  = "Iv1.b507a08c87ecfe98"  # GitHub Copilot CLI client ID
GITHUB_DEVICE_URL = "https://github.com/login/device/code"
GITHUB_TOKEN_URL  = "https://github.com/login/oauth/access_token"
GITHUB_SCOPES     = "read:user"


# ─────────────────────────────────────────
# Schemas
# ─────────────────────────────────────────
class OpenAISetup(BaseModel):
    api_key: str

class GeminiSetup(BaseModel):
    api_key: str

class SaveConfig(BaseModel):
    providers: dict  # { "openai": {...}, "gemini": {...}, "copilot": {...} }
    default_model: str = "gpt-4.1"


# ─────────────────────────────────────────
# Helpers
# ─────────────────────────────────────────
def write_env(config: dict):
    """Ghi .env từ config dict."""
    lines = ["# Generated by OpenClaw Gateway bootstrap\n"]

    if config.get("openai", {}).get("api_key"):
        lines.append(f'OPENAI_API_KEY={config["openai"]["api_key"]}\n')

    if config.get("gemini", {}).get("api_key"):
        lines.append(f'GEMINI_API_KEY={config["gemini"]["api_key"]}\n')

    if config.get("copilot", {}).get("token"):
        lines.append(f'COPILOT_TOKEN={config["copilot"]["token"]}\n')

    lines.append(f'DEFAULT_MODEL={config.get("default_model", "gpt-4.1")}\n')
    lines.append('PROJECTS_ROOT=/projects\n')
    lines.append('CHROMA_HOST=chromadb\n')
    lines.append('CHROMA_PORT=8000\n')
    lines.append('OLLAMA_HOST=ollama\n')
    lines.append('OLLAMA_PORT=11434\n')
    lines.append('EMBED_MODEL=nomic-embed-text\n')

    ENV_FILE.parent.mkdir(parents=True, exist_ok=True)
    ENV_FILE.write_text("".join(lines))


def read_config() -> dict:
    if CONFIG_FILE.exists():
        return json.loads(CONFIG_FILE.read_text())
    return {}


def save_config(config: dict):
    CONFIG_FILE.parent.mkdir(parents=True, exist_ok=True)
    CONFIG_FILE.write_text(json.dumps(config, indent=2))


# ─────────────────────────────────────────
# Routes
# ─────────────────────────────────────────
@router.get("/status")
async def bootstrap_status():
    """Trạng thái bootstrap hiện tại."""
    config = read_config()
    return {
        "bootstrapped": bool(ENV_FILE.exists()),
        "providers": {
            "openai":  bool(config.get("openai", {}).get("api_key")),
            "gemini":  bool(config.get("gemini", {}).get("api_key")),
            "copilot": bool(config.get("copilot", {}).get("token")),
        }
    }


# ── OpenAI ──────────────────────────────
@router.post("/openai/verify")
async def verify_openai(body: OpenAISetup):
    """Test API key bằng cách gọi models list."""
    async with httpx.AsyncClient() as client:
        resp = await client.get(
            "https://api.openai.com/v1/models",
            headers={"Authorization": f"Bearer {body.api_key}"},
            timeout=10,
        )
    if resp.status_code == 200:
        return {"valid": True, "message": "OpenAI key verified ✓"}
    raise HTTPException(status_code=400, detail=f"Invalid OpenAI key: {resp.status_code}")


# ── Gemini ───────────────────────────────
@router.post("/gemini/verify")
async def verify_gemini(body: GeminiSetup):
    """Test Gemini key."""
    async with httpx.AsyncClient() as client:
        resp = await client.get(
            f"https://generativelanguage.googleapis.com/v1beta/models?key={body.api_key}",
            timeout=10,
        )
    if resp.status_code == 200:
        return {"valid": True, "message": "Gemini key verified ✓"}
    raise HTTPException(status_code=400, detail=f"Invalid Gemini key: {resp.status_code}")


# ── GitHub Copilot Device Flow ────────────
@router.post("/copilot/start")
async def copilot_device_start():
    """
    Bắt đầu GitHub device flow.
    Trả về user_code và verification_uri để hiện lên UI.
    """
    async with httpx.AsyncClient() as client:
        resp = await client.post(
            GITHUB_DEVICE_URL,
            data={
                "client_id": GITHUB_CLIENT_ID,
                "scope": GITHUB_SCOPES,
            },
            headers={"Accept": "application/json"},
            timeout=10,
        )

    if resp.status_code != 200:
        raise HTTPException(status_code=502, detail="Failed to start GitHub device flow")

    data = resp.json()
    return {
        "device_code":      data["device_code"],
        "user_code":        data["user_code"],
        "verification_uri": data["verification_uri"],
        "expires_in":       data["expires_in"],
        "interval":         data.get("interval", 5),
    }


@router.post("/copilot/poll")
async def copilot_device_poll(body: dict):
    """
    Poll GitHub token endpoint sau khi user nhập code.
    Frontend gọi endpoint này mỗi {interval} giây.
    """
    device_code = body.get("device_code")
    if not device_code:
        raise HTTPException(status_code=400, detail="device_code required")

    async with httpx.AsyncClient() as client:
        resp = await client.post(
            GITHUB_TOKEN_URL,
            data={
                "client_id":   GITHUB_CLIENT_ID,
                "device_code": device_code,
                "grant_type":  "urn:ietf:params:oauth:grant-type:device_code",
            },
            headers={"Accept": "application/json"},
            timeout=10,
        )

    data = resp.json()

    if "access_token" in data:
        return {"status": "success", "token": data["access_token"]}

    error = data.get("error", "unknown")
    if error == "authorization_pending":
        return {"status": "pending"}
    if error == "slow_down":
        return {"status": "slow_down"}
    if error in ("expired_token", "access_denied"):
        raise HTTPException(status_code=400, detail=f"Device flow failed: {error}")

    return {"status": "pending"}


# ── Save & Generate .env ─────────────────
@router.post("/save")
async def save_bootstrap(body: SaveConfig):
    """
    Lưu config và generate .env.
    Gateway sẽ cần restart để load .env mới.
    """
    config = {**body.providers, "default_model": body.default_model}
    save_config(config)
    write_env(config)

    return {
        "status": "saved",
        "message": "Configuration saved. Gateway will restart now.",
        "env_file": str(ENV_FILE),
    }
